### ISSUE TITLE
Dimension in featureVector

### ISSUE THREAD

**Issue by NguyenThaiHoc1** [dnikolic98/CV-skill-extraction#1]
I have run your code and your dataset 
I receive an error 
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 342 and the array at index 1 has size 293

Hope you help me fix this errors
Thanks you for watching 
Thai Hoc

**Comment by dnikolic98** [comment]
Hey Thai,

I haven't really commited much when I was working on the project last time. I have deleted all unimportent files in the repo and updated the last version of the extractor so **I suggest you to download a clean version of the repo**.

I have trained the model on one, three and six neighbours and you can see results for that in RESULTS folder. Also, I have put an example of predicting and training.

If you get stuck on anything, project is based on this article:
[https://towardsdatascience.com/deep-learning-for-specific-information-extraction-from-unstructured-texts-12c5b9dceada
](url)


Disclaimer:
- inputExtractor is really unoptimised and slow, same could be said for some other parts of the code
- comments my not be a true representation of what some functions do

Hope I was helpful,
Dario

**Comment by NguyenThaiHoc1** [comment]
Thanks your for answer
I still download your new version but 
I get an error the same the old version 
You can see help me to fix this errors ? I'm a beginer in NLP Problems, your example in Medium is very good so I want to base on your code to learning more 

I hope you can help to fix an error (i run file training_example)
**Error**
Traceback (most recent call last):
  File "training_example.py", line 29, in <module>
    phrases, context, np_tags, context_tags, row[1].strip().split("|"))
  File "/media/DATA/THAIHOC/CV-skill-extraction-master/preprocessor.py", line 52, in preprocess
    current_context_vec = self.concat(context[i], context_tags[i])
  File "/media/DATA/THAIHOC/CV-skill-extraction-master/preprocessor.py", line 25, in concat
    ret_array = np.vstack([ret_array, self.featureVector.vectorise(phrase[i], tags[i])])
  File "<__array_function__ internals>", line 6, in vstack
  File "/media/DATA/THAIHOC/pos_env/lib/python3.6/site-packages/numpy/core/shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 342 and the array at index 1 has size 293
I run on LINUX
Thanks you for reply 
Thai Hoc

**Comment by ajinkya2903** [comment]
Hey, @NguyenThaiHoc1 Even I am facing the same error even after I tried changing some parameters. Have you solved it? If yes can you please help me in solving it? Thank You.

**Comment by raghulkrishna** [comment]
is this error resolved?

**Comment by raghulkrishna** [comment]
> Hey, @NguyenThaiHoc1 Even I am facing the same error even after I tried changing some parameters. Have you solved it? If yes can you please help me in solving it? Thank You.

have you tried predicting ?

**Comment by raghulkrishna** [comment]
> Thanks your for answer
> I still download your new version but
> I get an error the same the old version
> You can see help me to fix this errors ? I'm a beginer in NLP Problems, your example in Medium is very good so I want to base on your code to learning more
> 
> I hope you can help to fix an error (i run file training_example)
> **Error**
> Traceback (most recent call last):
> File "training_example.py", line 29, in
> phrases, context, np_tags, context_tags, row[1].strip().split("|"))
> File "/media/DATA/THAIHOC/CV-skill-extraction-master/preprocessor.py", line 52, in preprocess
> current_context_vec = self.concat(context[i], context_tags[i])
> File "/media/DATA/THAIHOC/CV-skill-extraction-master/preprocessor.py", line 25, in concat
> ret_array = np.vstack([ret_array, self.featureVector.vectorise(phrase[i], tags[i])])
> File "<**array_function** internals>", line 6, in vstack
> File "/media/DATA/THAIHOC/pos_env/lib/python3.6/site-packages/numpy/core/shape_base.py", line 283, in vstack
> return _nx.concatenate(arrs, 0)
> File "<**array_function** internals>", line 6, in concatenate
> ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 342 and the array at index 1 has size 293
> I run on LINUX
> Thanks you for reply
> Thai Hoc

have you tried predicting?

**Comment by jigsawcoder** [comment]
> Thanks your for answer
> I still download your new version but
> I get an error the same the old version
> You can see help me to fix this errors ? I'm a beginer in NLP Problems, your example in Medium is very good so I want to base on your code to learning more
> 
> I hope you can help to fix an error (i run file training_example)
> **Error**
> Traceback (most recent call last):
> File "training_example.py", line 29, in
> phrases, context, np_tags, context_tags, row[1].strip().split("|"))
> File "/media/DATA/THAIHOC/CV-skill-extraction-master/preprocessor.py", line 52, in preprocess
> current_context_vec = self.concat(context[i], context_tags[i])
> File "/media/DATA/THAIHOC/CV-skill-extraction-master/preprocessor.py", line 25, in concat
> ret_array = np.vstack([ret_array, self.featureVector.vectorise(phrase[i], tags[i])])
> File "<**array_function** internals>", line 6, in vstack
> File "/media/DATA/THAIHOC/pos_env/lib/python3.6/site-packages/numpy/core/shape_base.py", line 283, in vstack
> return _nx.concatenate(arrs, 0)
> File "<**array_function** internals>", line 6, in concatenate
> ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 342 and the array at index 1 has size 293
> I run on LINUX
> Thanks you for reply
> Thai Hoc

Is this error resolved? If yes, how??
